import Head from 'next/head';
import React, { ReactNode } from 'react';
import Navbar from './Navbar';
import { useSession } from 'next-auth/react';

interface ILayout {
  children: ReactNode;
}

const Layout: React.FC<ILayout> = ({ children }) => {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Authentication</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar email={session?.user?.email as string} />
      {children}
    </>
  )
}

export default Layout